### PR TITLE
Adopt PSR-2

### PR DESCRIPTION
**Pull request by svenluijten**
This PR is the working branch to PSR-2-ify the codebase of this project, as discussed in #7.

### CODE REVIEW

**Comment by svenluijten** [comment]
Will continue work on this tomorrow. 

FYI, tests would defintely help simplify the changes made here 😉

**Comment by weotch** [comment]
Ha, yeah, no doubt.  It's a great regret of mind that we didn't TDD this.

Thanks for all your efforts here!

**Comment by svenluijten** [comment]
Ready for review! Take your time with this one, there's also a few places I ended up simplifying logic. Mainly constructions like this:

```php
if ($condition) {
    return $foo;
} else {
    return $bar;
}
```

which I changed to:

```php
if ($condition) {
    return $foo;
}

return $bar;
```

**Comment by weotch** [comment]
Dude, amazing.  Thanks!

My next steps are gonna start a Laravel 5.4 branch ( #6 ), probably next week, and add create some integration tests first, as part of that.  Then, with that done, I'll merge your PR in and see if the tests still pass.  Then address L5.4 support.

**Comment by svenluijten** [comment]
👍 Sounds good!

**Comment by minedun6** [comment]
Project looking promising !!
Would love to see what we can do with this ^_^.

**Comment by svenluijten** [comment]
Will resolve conflicts later today 🙂

**Comment by weotch** [comment]
Sorry bout that, was pretty trivial so I did it ;)

**Pull request merged**
